const {Sequelize, DataTypes, QueryTypes} = require("sequelize");
module.exports = (sequelize, Sequelize,DataTypes) => {
    const appraisals = sequelize.define("appraisals", {
     userid:{
      type:DataTypes.INTEGER,
      allowNull:false
     },
      understanding_job:{
        type:DataTypes.STRING,
        allowNull:false
      },
      fulfillment_job:{
        type:DataTypes.STRING,
        allowNull:false
      },
      capacity_work:{
        type:DataTypes.STRING,
        allowNull:false
      },
      quality_work:{
        type:DataTypes.STRING,
        allowNull:false
      },
      learning_improvement:{
        type:DataTypes.STRING,
        allowNull:false
      },
      communication:{
        type:DataTypes.STRING,
        allowNull:false
      },
      responsibility:{
        type:DataTypes.STRING,
        allowNull:false
      },
      initiative:{
        type:DataTypes.STRING,
        allowNull:false
      },
      motivation:{
        type:DataTypes.STRING,
        allowNull:false
      },
      adoptability:{
        type:DataTypes.STRING,
        allowNull:false
      },
      reliability:{
        type:DataTypes.STRING,
        allowNull:false
      },
      team_work:{
        type:DataTypes.STRING,
        allowNull:false
      },
      punctuality:{
        type:DataTypes.STRING,
        allowNull:false
      },
      presentation:{
        type:DataTypes.STRING,
        allowNull:false
      },
      politenesss_respect:{
        type:DataTypes.STRING,
        allowNull:false
      },
      interaction:{
        type:DataTypes.STRING,
        allowNull:false
      },
      interest_cst:{
        type:DataTypes.STRING,
        allowNull:false
      },
      contact_coordination:{
        type:DataTypes.STRING,
        allowNull:false
      },
      understanding_job_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      fulfillment_job_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      capacity_work_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      quality_work_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      learning_improvement_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      communication_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      responsibility_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      initiative_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      motivation_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      adoptability_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      reliability_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      team_work_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      punctuality_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      presentation_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      politenesss_respect_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      interaction_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      interest_cst_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      contact_coordination_comments:{
        type:DataTypes.STRING,
        allowNull:false
      },
      general_remarks:{
        type:DataTypes.STRING,
        allowNull:false
      },
      objective_next:{
        type:DataTypes.STRING,
        allowNull:false
      },
      proposal_staff:{
        type:DataTypes.STRING,
        allowNull:false
      },
      employee_remarks:{
        type:DataTypes.STRING,
        allowNull:false
      },
      evaluator_remarks:{
        type:DataTypes.STRING,
        allowNull:false
      },
      ceo_commensts:{
        type:DataTypes.STRING,
        allowNull:false
      }

    });
  
    return appraisals;
  };
  